#!/usr/bin/env bash
set -Eeuo pipefail

APP_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$APP_ROOT/.picture-flashcards.local.env"
RUNTIME_DIR="$APP_ROOT/.picture-flashcards-runtime"
LOG_DIR="$RUNTIME_DIR/logs"
API_PID_FILE="$RUNTIME_DIR/api.pid"
WEB_PID_FILE="$RUNTIME_DIR/web.pid"
DATA_DIR="$APP_ROOT/.picture-flashcards-data"
DEFAULT_APP_PORT=5016
USE_SAVED_CONFIG=false

fail() {
  echo "Install failed: $*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage: ./install.sh [--use-saved-config]

Without arguments, the installer asks for the frontend port and defaults to
5016. The API uses the next port internally and is proxied through the
frontend, so only the configured frontend port needs to be exposed.

--use-saved-config  Reuse .picture-flashcards.local.env without prompting.
EOF
}

valid_port() {
  [[ "$1" =~ ^[0-9]{1,5}$ ]] || return 1
  local port_number=$((10#$1))
  (( port_number >= 1 && port_number <= 65535 ))
}

port_in_use() {
  local port="$1"
  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"$port" -sTCP:LISTEN -t >/dev/null 2>&1
    return
  fi
  if command -v ss >/dev/null 2>&1; then
    ss -ltnH 2>/dev/null | awk -v wanted=":$port" '$4 ~ wanted "$" { found=1 } END { exit !found }'
    return
  fi
  return 1
}

stop_pid_file() {
  local pid_file="$1"
  [[ -f "$pid_file" ]] || return 0

  local pid
  pid="$(cat "$pid_file" 2>/dev/null || true)"
  if [[ "$pid" =~ ^[0-9]+$ ]] && kill -0 "$pid" 2>/dev/null; then
    if command -v pkill >/dev/null 2>&1; then
      pkill -TERM -P "$pid" 2>/dev/null || true
    fi
    kill "$pid" 2>/dev/null || true
    for _ in 1 2 3 4 5; do
      kill -0 "$pid" 2>/dev/null || break
      sleep 1
    done
    if kill -0 "$pid" 2>/dev/null; then
      kill -KILL "$pid" 2>/dev/null || true
    fi
  fi
  rm -f "$pid_file"
}

stop_services() {
  stop_pid_file "$WEB_PID_FILE"
  stop_pid_file "$API_PID_FILE"
}

ensure_runtime() {
  command -v node >/dev/null 2>&1 || fail "Node.js is required. Install Node.js 20 or newer, then run this script again."

  local node_major
  node_major="$(node -p 'process.versions.node.split(".")[0]')"
  (( node_major >= 20 )) || fail "Node.js 20 or newer is required; found $(node --version)."

  if command -v pnpm >/dev/null 2>&1; then
    PNPM_CMD=(pnpm)
  elif command -v corepack >/dev/null 2>&1; then
    PNPM_CMD=(corepack pnpm)
  else
    fail "pnpm or Corepack is required. Install Node.js with Corepack enabled, then run this script again."
  fi
}

load_or_choose_port() {
  if [[ "$USE_SAVED_CONFIG" == true ]]; then
    [[ -f "$CONFIG_FILE" ]] || fail "No saved configuration exists. Run ./install.sh first."
    # This file is generated by this script and contains only numeric ports.
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
    valid_port "${APP_PORT:-}" || fail "Saved APP_PORT is invalid."
    valid_port "${API_PORT:-}" || fail "Saved API_PORT is invalid."
    return
  fi

  local requested_port
  if [[ -t 0 ]]; then
    read -r -p "Frontend port [$DEFAULT_APP_PORT]: " requested_port
  else
    requested_port=""
    echo "No interactive terminal detected; using frontend port $DEFAULT_APP_PORT."
  fi
  requested_port="${requested_port:-$DEFAULT_APP_PORT}"

  valid_port "$requested_port" || fail "Choose a port from 1 to 65535."
  APP_PORT=$((10#$requested_port))
  API_PORT=$((APP_PORT + 1))
  (( API_PORT <= 65535 )) || fail "The selected port is too high; its internal API port would exceed 65535."
}

write_config() {
  umask 077
  cat > "$CONFIG_FILE" <<EOF
# Generated by install.sh. This file is local to this app and is ignored by git.
APP_PORT=$APP_PORT
API_PORT=$API_PORT
EOF
}

install_dependencies_and_build() {
  cd "$APP_ROOT"
  echo "Installing workspace dependencies locally..."
  "${PNPM_CMD[@]}" install --frozen-lockfile

  echo "Checking the API and frontend..."
  "${PNPM_CMD[@]}" --filter @workspace/api-server run typecheck
  "${PNPM_CMD[@]}" --filter @workspace/picture-flashcards run typecheck

  echo "Building the API..."
  "${PNPM_CMD[@]}" --filter @workspace/api-server run build

  echo "Building the frontend..."
  PORT="$APP_PORT" API_PORT="$API_PORT" BASE_PATH=/ \
    "${PNPM_CMD[@]}" --filter @workspace/picture-flashcards run build
}

start_services() {
  mkdir -p "$LOG_DIR" "$DATA_DIR"
  stop_services

  echo "Starting the local API on 127.0.0.1:$API_PORT..."
  nohup env \
    NODE_ENV=production \
    HOST=127.0.0.1 \
    PORT="$API_PORT" \
    FLASHCARDS_DATA_DIR="$DATA_DIR" \
    "${PNPM_CMD[@]}" --filter @workspace/api-server run start \
    > "$LOG_DIR/api.log" 2>&1 &
  echo "$!" > "$API_PID_FILE"

  echo "Starting the frontend on port $APP_PORT..."
  nohup env \
    NODE_ENV=production \
    PORT="$APP_PORT" \
    API_PORT="$API_PORT" \
    BASE_PATH=/ \
    "${PNPM_CMD[@]}" --filter @workspace/picture-flashcards run serve \
    > "$LOG_DIR/web.log" 2>&1 &
  echo "$!" > "$WEB_PID_FILE"

  if command -v curl >/dev/null 2>&1; then
    for _ in 1 2 3 4 5 6 7 8 9 10; do
      if curl -fsS "http://127.0.0.1:$API_PORT/api/healthz" >/dev/null 2>&1 \
        && curl -fsS "http://127.0.0.1:$APP_PORT/" >/dev/null 2>&1; then
        return
      fi
      sleep 1
    done
    echo "The services were started, but health checks did not complete." >&2
    echo "Check $LOG_DIR/api.log and $LOG_DIR/web.log." >&2
  fi
}

main() {
  case "${1:-}" in
    "")
      ;;
    --use-saved-config)
      USE_SAVED_CONFIG=true
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 2
      ;;
  esac

  ensure_runtime
  load_or_choose_port

  if [[ "$USE_SAVED_CONFIG" == false ]]; then
    stop_services
    port_in_use "$APP_PORT" && fail "Frontend port $APP_PORT is already in use."
    port_in_use "$API_PORT" && fail "Internal API port $API_PORT is already in use."
    write_config
  fi

  install_dependencies_and_build
  start_services

  echo
  echo "Picture Flashcards is installed and running."
  echo "Open: http://127.0.0.1:$APP_PORT/"
  echo "Data: $DATA_DIR"
  echo "Logs: $LOG_DIR"
}

main "$@"